% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{geometry} \geometry{top=1cm,left=1cm,bottom=1cm,right=1cm}
\usepackage{threeparttable}
\usepackage{booktabs}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={EMEP4UK input files QAQC document - UK/EIRE \& EU},
  pdfauthor={Sam Tomlinson},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{EMEP4UK input files QAQC document - UK/EIRE \& EU}
\author{Sam Tomlinson}
\date{2025-10-07}

\begin{document}
\maketitle

\section{UK/EIRE INPUT FILES}\label{ukeire-input-files}

\subsection{METADATA}\label{metadata}

\textbf{Project:} NFC

\textbf{Scenario:} BASE

\textbf{Git Repo:} \url{https://github.com/oSamTo/EMEP_inputs}

\textbf{JASMIN dir:} /gws/ssde/j25b/ceh\_generic/samtom

\textbf{Output dir:}
EMEP\_inputs/outputs/NFC/BASE/EMEP4UKv5.0/inv2025/UKEIRE/annual/TPannual\_allISO

\textbf{EMEP version:} v5.0

\vspace{\baselineskip}

Input files processed to 0.01\(^\circ\) x 0.01\(^\circ\) resolution, in
WGS84.

\vspace{\baselineskip}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.0789}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1184}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1316}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1447}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1316}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1316}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1316}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1316}}@{}}
\caption{Metadata of inputs}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Species
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Inv\_Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Emis\_Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
temp\_res
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_sec
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_res
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_crs
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Species
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Inv\_Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Emis\_Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
temp\_res
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_sec
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_res
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_crs
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
UK & sox & 2025 & 2023 & annual & SNAP & 1km & BNG \\
Eire & sox & 2025 & 2023 & annual & GNFR & 1km & TM65 \\
SEA & sox & as above & as above & N/A & N/A & N/A & N/A \\
\end{longtable}

Notes:

\begin{itemize}
\item
  Emissions from the UK and Eire are processed to consistent sector
  categories (see /data/lookups/EMEP\_sectors.csv) and masked to a
  UK+10km mask. EMEP/CEIP emissions take precedence outside of this
  mask.
\item
  The 10km strip from the land territory into the sea is combined (UK +
  Eire) to a `SEA' ISO code, for all sectors.
\item
  Emissions maps are pre-processed from 1km x 1km BNG (UK) and 1km x 1km
  Irish Grid TM65 (Eire) into WGS84 lat lon, at 0.01\(^\circ\) x
  0.01\(^\circ\) resolution.

  \begin{itemize}
  \tightlist
  \item
    This is done in /gws/ssde/j25b/ceh\_generic/inventory\_processor
  \end{itemize}
\end{itemize}

\newpage

\subsection{\texorpdfstring{MAP: TOTAL EMISSION
ANNUM\textsuperscript{-1}}{MAP: TOTAL EMISSION ANNUM-1}}\label{map-total-emission-annum-1}

\begin{figure}[h]

{\centering \includegraphics[width=0.7\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/UKEIRE/annual/TPannual_allISO/plots/e2023/sox_UKEIRE_2023emis_2023map_2025inv_1_UKTOTMAP} 

}

\caption{UK/Eire total sox emissions annum-1 (Non-UK/Eire emissions for context).}\label{fig:unnamed-chunk-2}
\end{figure}

\vspace{\baselineskip}

\begin{longtable}[]{@{}ccccc@{}}
\caption{Annual emissions of sox per ISO.}\tabularnewline
\toprule\noalign{}
Area & Species & Total\_kt & mean\_t & max\_t \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Area & Species & Total\_kt & mean\_t & max\_t \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
UK & sox & 91.17 & 0.26 & 5101.40 \\
Eire & sox & 7.28 & 0.07 & 359.76 \\
SEA & sox & 3.98 & 0.04 & 50.43 \\
Overall & sox & 102.43 & 0.18 & 5101.40 \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  N.B. UK and Eire totals in Table 2 are only on-land emissions.
\end{itemize}

\newpage

\subsection{PROCESSING FLOW}\label{processing-flow}

The processing in Figure \ref{fig:fig-proc1} shows total emissions as
taken from the maps (inv\_spatial), the inventory table (inv\_table),
the scaled maps (spatial\_scaled), and the area aggregated totals using
the mask.

N.B. the map used is not necessarily the same as the emissions year
(e.g.~MapEire from 2019).

\begin{figure}[h]

{\centering \includegraphics[width=0.6\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/UKEIRE/annual/TPannual_allISO/plots/e2023/sox_UKEIRE_2023emis_2023map_2025inv_2_UKINVBAR} 

}

\caption{Emissions processing from source to area-scaled totals.}\label{fig:fig-proc1}
\end{figure}

Total sox in UK \& Eire, processed: 114.2 kt + 7.4 kt = 121.6 kt.
Spatial breakdown :

\begin{itemize}
\item
  UK = 91.2 kt
\item
  Eire = 7.3 kt
\item
  SEA = 4 kt
\item
  Outwith 10km = 19.2 kt
\end{itemize}

\textbf{Overall: Of 121.6 kt processed, 102.4 kt are input to .nc file,
and 19.2 kt are masked (dropped).}

Figure \ref{fig:fig-proc2} shows the data progressing to NetCDF inputs -
`outwith' data (data outside 10km buffer) is dropped.

\begin{figure}[h]

{\centering \includegraphics[width=0.6\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/UKEIRE/annual/TPannual_allISO/plots/e2023/sox_UKEIRE_2023emis_2023map_2025inv_3_UKNCBAR} 

}

\caption{Area-scaled toals to NetCDF input data.}\label{fig:fig-proc2}
\end{figure}

Emissions coming from processed inventories to NetCDF inputs; `outwith'
emissions (emissions outside 10km sea buffer) are masked and not used
for UK/Eire (replaced by EMEP-EU).

\newpage

\subsection{ALTERNATIVE EMISSIONS -
INPUT}\label{alternative-emissions---input}

\textbf{Input files:}

UK: No alternative (non-inventory) sources of emissions were used for
sox.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1515}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0909}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1970}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1667}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1818}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2121}}@{}}
\caption{No alternative input files}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
GNFR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
source\_diff
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
source\_pt
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
alt\_emis\_t
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
emis\_delta\_t
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
GNFR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
source\_diff
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
source\_pt
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
alt\_emis\_t
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
emis\_delta\_t
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
No files & NA & NA & NA & NA & NA \\
\end{longtable}

Eire: No alternative (non-inventory) sources of emissions were used for
sox.

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1515}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0909}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1970}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1667}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1818}}
  >{\centering\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2121}}@{}}
\caption{No alternative input files}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
GNFR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
source\_diff
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
source\_pt
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
alt\_emis\_t
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
emis\_delta\_t
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
GNFR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
source\_diff
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
source\_pt
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
alt\_emis\_t
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
emis\_delta\_t
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
No files & NA & NA & NA & NA & NA \\
\end{longtable}

\begin{figure}[h]

{\centering \includegraphics[width=0.7\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/UKEIRE/annual/TPannual_allISO/plots/e2023/sox_UKEIRE_2023emis_2023map_2025inv_3b_UKALTTOTBAR} 

}

\caption{Inventory emissions vs altered emissions - TOTAL (if any).}\label{fig:fig-altemistot}
\end{figure}

\begin{verbatim}
## [1] "No sectoral changes."
\end{verbatim}

\newpage

\subsection{\texorpdfstring{MAP: SECTORAL EMISSIONS
ANNUM\textsuperscript{-1} - NC
FILE}{MAP: SECTORAL EMISSIONS ANNUM-1 - NC FILE}}\label{map-sectoral-emissions-annum-1---nc-file}

\subsubsection{UK and Eire temporal schema:
annual}\label{uk-and-eire-temporal-schema-annual}

\begin{figure}[h]

{\centering \includegraphics[width=0.75\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/UKEIRE/annual/TPannual_allISO/plots/e2023/sox_UKEIRE_2023emis_2023map_2025inv_6_UKANNSECMAP} 

}

\caption{UK/Eire total sox emissions sector-1 annum-1}\label{fig:unnamed-chunk-5}
\end{figure}

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.3143}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1143}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1000}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1000}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1286}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1143}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1286}}@{}}
\caption{sox emissions (kt) per sector per ISO (red values have
alternative data sources) (Totals match Processing Flow
totals)}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
GB
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
IE
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SEA
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ncTotal
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
OW
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
GB
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
IE
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SEA
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ncTotal
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
OW
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
A\_PublicPower & 26.747 & 0.71 & 0 & 27.457 & 1.625 & 29.082 \\
B\_Industry & 41.851 & 1.465 & 0 & 43.316 & 0 & 43.316 \\
C\_OtherStationaryComb & 15.032 & 4.935 & 0 & 19.967 & 0 & 19.967 \\
D\_Fugitive & 0 & 0 & 0 & 0.000 & 0 & 0.000 \\
E\_Solvents & 0.796 & 0 & 0 & 0.796 & 0 & 0.796 \\
F\_RoadTransport & 0.397 & 0.04 & 0 & 0.437 & 0 & 0.437 \\
G\_Shipping & 0 & 0.025 & 0.057 & 0.082 & 0.03 & 0.112 \\
H\_Aviation & 0 & 0.095 & 0 & 0.095 & 0 & 0.095 \\
I\_Offroad & 5.455 & 0.003 & 3.925 & 9.383 & 17.503 & 26.886 \\
J\_Waste & 0.888 & 0.002 & 0 & 0.890 & 0 & 0.890 \\
K\_AgriLivestock & 0 & 0 & 0 & 0.000 & 0 & 0.000 \\
L\_AgriOther & 0 & 0 & 0 & 0.000 & 0 & 0.000 \\
M\_Other & 0 & 0 & 0 & 0.000 & 0 & 0.000 \\
Total & 91.166 & 7.275 & 3.982 & 102.423 & 19.158 & 121.581 \\
\end{longtable}

\newpage

\subsection{\texorpdfstring{EMISSIONS
MONTH\textsuperscript{-1}}{EMISSIONS MONTH-1}}\label{emissions-month-1}

\subsubsection{UK and Eire temporal schema:
annual}\label{uk-and-eire-temporal-schema-annual-1}

Source: EMEP v5.0 schema: data/temporal/EMEP4UKv5.0/

\begin{figure}[h]

{\centering \includegraphics[width=0.6\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/UKEIRE/annual/TPannual_allISO/plots/e2023/sox_UKEIRE_2023emis_2023map_2025inv_4_UKMONTOTLINE} 

}

\caption{Emissions of sox month-1}\label{fig:fig-montot}
\end{figure}

Total monthly emissions of sox in UK, Eire and the SEA buffer. As annual
emissions input into NetCDF, using model profiles.

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0795}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0795}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0682}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0909}}@{}}
\caption{Total monthly sox emissions (kt)}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
IE & 0.87 & 0.83 & 0.84 & 0.78 & 0.62 & 0.54 & 0.33 & 0.29 & 0.40 & 0.54
& 0.59 & 0.66 & 7.29 \\
SEA & 0.30 & 0.33 & 0.36 & 0.35 & 0.33 & 0.34 & 0.33 & 0.31 & 0.32 &
0.34 & 0.34 & 0.32 & 3.97 \\
UK & 8.84 & 8.73 & 9.49 & 8.67 & 6.99 & 7.08 & 6.33 & 5.62 & 6.50 & 7.38
& 7.51 & 8.13 & 91.27 \\
Total & 10.01 & 9.89 & 10.69 & 9.80 & 7.94 & 7.96 & 6.99 & 6.22 & 7.22 &
8.26 & 8.44 & 9.11 & 102.53 \\
\end{longtable}

\newpage

\subsection{\texorpdfstring{MAP: EMISSIONS
MONTH\textsuperscript{-1}}{MAP: EMISSIONS MONTH-1}}\label{map-emissions-month-1}

Also see Table 5 above for totals.

\begin{figure}[h]

{\centering \includegraphics[width=0.85\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/UKEIRE/annual/TPannual_allISO/plots/e2023/sox_UKEIRE_2023emis_2023map_2025inv_7_UKMONTOTMAP} 

}

\caption{UK/Eire total sox emissions month-1}\label{fig:unnamed-chunk-8}
\end{figure}

\newpage

\subsection{\texorpdfstring{SECTORAL EMISSIONS
MONTH\textsuperscript{-1}}{SECTORAL EMISSIONS MONTH-1}}\label{sectoral-emissions-month-1}

\subsubsection{UK and Eire temporal schema:
annual}\label{uk-and-eire-temporal-schema-annual-2}

Source: EMEP v5.0 schema: data/temporal/EMEP4UKv5.0/

\begin{figure}[h]

{\centering \includegraphics[width=0.8\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/UKEIRE/annual/TPannual_allISO/plots/e2023/sox_UKEIRE_2023emis_2023map_2025inv_5_UKMONSECLINE} 

}

\caption{Emissions (kt) of sox month-1 sector-1}\label{fig:unnamed-chunk-9}
\end{figure}

N.B. as UK data starts in SNAP sectors \& Eire data in GNFR sectors, UK
\& Eire sectoral monthly emissions are sometimes flat

\vspace{\baselineskip}

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.2056}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0654}}@{}}
\caption{Monthly sox emissions (kt) per sector (UK)}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
A\_PublicPower & UK & 2.68 & 2.51 & 2.77 & 2.48 & 1.86 & 2.03 & 2.00 &
1.67 & 1.94 & 2.13 & 2.11 & 2.57 & 26.75 \\
B\_Industry & UK & 3.49 & 3.65 & 3.91 & 3.70 & 3.40 & 3.45 & 3.29 & 3.08
& 3.27 & 3.54 & 3.58 & 3.50 & 41.86 \\
C\_OtherStationaryComb & UK & 2.09 & 1.96 & 2.15 & 1.83 & 1.10 & 0.94 &
0.41 & 0.28 & 0.66 & 1.05 & 1.18 & 1.44 & 15.09 \\
D\_Fugitive & UK & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00
& 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
E\_Solvents & UK & 0.06 & 0.06 & 0.06 & 0.07 & 0.07 & 0.07 & 0.07 & 0.07
& 0.07 & 0.07 & 0.06 & 0.06 & 0.79 \\
F\_RoadTransport & UK & 0.03 & 0.03 & 0.03 & 0.03 & 0.03 & 0.03 & 0.03 &
0.03 & 0.03 & 0.04 & 0.03 & 0.03 & 0.37 \\
G\_Shipping & UK & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00
& 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
H\_Aviation & UK & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00
& 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
I\_Offroad & UK & 0.42 & 0.45 & 0.49 & 0.48 & 0.45 & 0.47 & 0.45 & 0.42
& 0.44 & 0.47 & 0.47 & 0.44 & 5.45 \\
J\_Waste & UK & 0.07 & 0.07 & 0.07 & 0.07 & 0.07 & 0.07 & 0.07 & 0.07 &
0.07 & 0.07 & 0.07 & 0.07 & 0.84 \\
K\_AgriLivestock & UK & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 &
0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
L\_AgriOther & UK & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 &
0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
M\_Other & UK & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 &
0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
Total & - & 8.84 & 8.73 & 9.48 & 8.66 & 6.98 & 7.06 & 6.32 & 5.62 & 6.48
& 7.37 & 7.50 & 8.11 & 91.15 \\
\end{longtable}

\vspace{\baselineskip}

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.2056}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0561}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0654}}@{}}
\caption{Monthly sox emissions (kt) per sector (EIRE)}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
A\_PublicPower & IE & 0.06 & 0.06 & 0.06 & 0.06 & 0.06 & 0.06 & 0.06 &
0.06 & 0.05 & 0.06 & 0.06 & 0.06 & 0.71 \\
B\_Industry & IE & 0.12 & 0.12 & 0.13 & 0.13 & 0.12 & 0.12 & 0.12 & 0.10
& 0.11 & 0.13 & 0.13 & 0.13 & 1.46 \\
C\_OtherStationaryComb & IE & 0.67 & 0.64 & 0.64 & 0.58 & 0.42 & 0.35 &
0.14 & 0.12 & 0.22 & 0.34 & 0.39 & 0.47 & 4.98 \\
D\_Fugitive & IE & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00
& 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
E\_Solvents & IE & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00
& 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
F\_RoadTransport & IE & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 &
0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
G\_Shipping & IE & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00
& 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
H\_Aviation & IE & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01 & 0.01
& 0.01 & 0.01 & 0.01 & 0.01 & 0.12 \\
I\_Offroad & IE & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00
& 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
J\_Waste & IE & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 &
0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
K\_AgriLivestock & IE & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 &
0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
L\_AgriOther & IE & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 &
0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
M\_Other & IE & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 &
0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
Total & - & 0.86 & 0.83 & 0.84 & 0.78 & 0.61 & 0.54 & 0.33 & 0.29 & 0.39
& 0.54 & 0.59 & 0.67 & 7.27 \\
\end{longtable}

\newpage

\section{EU INPUTS FILES}\label{eu-inputs-files}

\subsection{METADATA}\label{metadata-1}

\textbf{Project:} NFC

\textbf{Git Repo:} \url{https://github.com/oSamTo/EMEP_inputs}

\textbf{JASMIN dir:} /gws/ssde/j25b/ceh\_generic/samtom/EMEP\_inputs

\textbf{Output dir:}
outputs/NFC/BASE/EMEP4UKv5.0/inv2025/EU/annual/TPannual\_allISO

\textbf{EMEP version:} v5.0

\vspace{\baselineskip}

Input files processed to 0.1\(^\circ\) x 0.1\(^\circ\) resolution, in
WGS84.

\vspace{\baselineskip}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1139}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1139}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1392}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}
  >{\centering\arraybackslash}p{(\linewidth - 14\tabcolsep) * \real{0.1266}}@{}}
\caption{Metadata of inputs}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Species
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Inv\_Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Emis\_Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
temp\_res
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_sec
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_res
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_crs
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Area
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Species
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Inv\_Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Emis\_Year
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
temp\_res
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_sec
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_res
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
orig\_crs
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
EU ISOs & sox & 2025 & 2023 & annual & GNFR & 0.1 & WGS84 \\
\end{longtable}

\textbf{EMEP ISO codes:} AL, AT, BE, BG, DK, FI, FR, GR, HU, IS, IE, IT,
LU, NL, NO, PL, PT, RO, ES, SE, CH, TR, GB, BAS, NOS, ATL, MED, BLS, BY,
UA, MD, EE, LV, LT, CZ, SK, SI, HR, BA, MK, KZ, GE, CY, AM, MT, LI, DE,
RU, MC, NOA, KG, AZ, RS, ME, UZ, TM, CAS, TJ, RUE, AST

Notes:

\begin{itemize}
\item
  Emissions from the EU (and wider) domain remain in GNFR sectors (see
  /data/lookups/EMEP\_sectors.csv) with UK+10km data masked out.
  EMEP/CEIP emissions take precedence outside of this mask.
\item
  Emissions data are provided in WGS84 lat lon, at 0.1\(^\circ\) x
  0.1\(^\circ\) resolution.

  \begin{itemize}
  \tightlist
  \item
    This is done in /gws/ssde/j25b/ceh\_generic/inventory\_processor
  \end{itemize}
\end{itemize}

\newpage

\subsection{\texorpdfstring{MAP: TOTAL EMISSION
ANNUM\textsuperscript{-1}}{MAP: TOTAL EMISSION ANNUM-1}}\label{map-total-emission-annum-1-1}

\begin{figure}[h]

{\centering \includegraphics[width=0.9\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/EU/annual/TPannual_allISO/plots/e2023/sox_EU_2023emis_2023map_2025inv_8_EUTOTMAP} 

}

\caption{EU total sox emissions annum-1 (UK/Eire emissions for context).}\label{fig:unnamed-chunk-13}
\end{figure}

\vspace{\baselineskip}

\begin{longtable}[]{@{}ccccc@{}}
\caption{Annual emissions of sox per ISO.}\tabularnewline
\toprule\noalign{}
Area & Species & Total\_kt & mean\_t & max\_t \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Area & Species & Total\_kt & mean\_t & max\_t \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
EU & sox & 10748.8 & 20.62 & 230125.8 \\
\end{longtable}

\begin{itemize}
\tightlist
\item
  N.B. EU totals in table above have UK \& Eire masked out.
\end{itemize}

\newpage

\subsection{PROCESSING FLOW}\label{processing-flow-1}

Figure \ref{fig:fig-procEU1} shows total EMEP emissions as taken from
EMEP/CEIP (inventory\_data) and emissions post processing
(processed\_data).

\begin{figure}[h]

{\centering \includegraphics[width=0.35\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/EU/annual/TPannual_allISO/plots/e2023/sox_EU_2023emis_2023map_2025inv_9_EUINVBAR} 

}

\caption{Emissions processing from source.}\label{fig:fig-procEU1}
\end{figure}

Total sox lost in EU domain, following processing: 102 kt. Spatial
breakdown :

\begin{longtable}[]{@{}ccccc@{}}
\caption{Emissions lost in EMEP domain per ISO.}\tabularnewline
\toprule\noalign{}
ISO & inventory\_kt & processed\_kt & lost\_kt & proc\_ratio \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
ISO & inventory\_kt & processed\_kt & lost\_kt & proc\_ratio \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
ATL & 112.9 & 110.6 & -2.3 & 0.980 \\
GB & 95.1 & 4.4 & -90.7 & 0.046 \\
IE & 7.4 & 0.0 & -7.4 & 0.000 \\
NOS & 25.7 & 24.0 & -1.7 & 0.934 \\
Total & 241.1 & 139.0 & -102.1 & 1.960 \\
\end{longtable}

Figure \ref{fig:fig-procEU2} shows the data progressing to NetCDF inputs
- emissions inside 10km sea buffer are masked and not used for EMEP-EU.

\begin{figure}[h]

{\centering \includegraphics[width=0.6\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/EU/annual/TPannual_allISO/plots/e2023/sox_EU_2023emis_2023map_2025inv_10_EUNCBAR} 

}

\caption{Processed toals to NetCDF input data.}\label{fig:fig-procEU2}
\end{figure}

\newpage

\subsection{\texorpdfstring{MAP: SECTORAL EMISSIONS
ANNUM\textsuperscript{-1}}{MAP: SECTORAL EMISSIONS ANNUM-1}}\label{map-sectoral-emissions-annum-1}

\subsubsection{EU temporal schema:
annual}\label{eu-temporal-schema-annual}

Source: EMEP v5.0 schema: data/temporal/EMEP4UKv5.0/

\begin{figure}[h]

{\centering \includegraphics[width=0.85\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/EU/annual/TPannual_allISO/plots/e2023/sox_EU_2023emis_2023map_2025inv_13_EUANNSECMAP} 

}

\caption{EMEP-EU total sox emissions sector-1 annum-1}\label{fig:unnamed-chunk-14}
\end{figure}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.2738}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.1190}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0952}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0833}}
  >{\centering\arraybackslash}p{(\linewidth - 16\tabcolsep) * \real{0.0952}}@{}}
\caption{sox emissions (kt) per sector in EU, plus UK proximal
ISOs}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
EU
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
FR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
NL
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
BE
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
DE
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ES
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
NOS
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ATL
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\centering
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
EU
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
FR
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
NL
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
BE
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
DE
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ES
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
NOS
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ATL
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
A\_PublicPower & 5239.86 & 5.63 & 1.83 & 0.92 & 69.01 & 3.92 & 0.00 &
0.00 \\
B\_Industry & 2524.76 & 52.43 & 14.42 & 15.77 & 125.03 & 47.24 & 0.00 &
0.00 \\
C\_OtherStationaryComb & 2118.01 & 9.35 & 0.47 & 1.73 & 15.16 & 14.39 &
0.00 & 0.00 \\
D\_Fugitive & 227.10 & 7.82 & 0.00 & 3.03 & 5.29 & 21.87 & 0.00 &
0.00 \\
E\_Solvents & 33.67 & 0.01 & 0.04 & 0.01 & 0.10 & 0.02 & 0.00 & 0.00 \\
F\_RoadTransport & 98.45 & 0.79 & 0.17 & 0.10 & 0.75 & 0.30 & 0.00 &
0.00 \\
G\_Shipping & 404.26 & 0.51 & 0.01 & 0.07 & 0.31 & 3.18 & 24.02 &
110.55 \\
H\_Aviation & 6.67 & 0.68 & 0.25 & 0.10 & 0.58 & 0.52 & 0.00 & 0.00 \\
I\_Offroad & 37.31 & 0.67 & 0.26 & 0.03 & 0.29 & 0.61 & 0.00 & 0.00 \\
J\_Waste & 7.14 & 0.32 & 0.06 & 0.01 & 0.10 & 1.56 & 0.00 & 0.00 \\
K\_AgriLivestock & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 &
0.00 \\
L\_AgriOther & 20.07 & 0.06 & 0.00 & 0.00 & 0.00 & 0.01 & 0.00 & 0.00 \\
M\_Other & 31.49 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 & 0.00 \\
Total & 10748.79 & 78.27 & 17.51 & 21.77 & 216.62 & 93.62 & 24.02 &
110.55 \\
\end{longtable}

\newpage

\subsection{\texorpdfstring{EMISSIONS
MONTH\textsuperscript{-1}}{EMISSIONS MONTH-1}}\label{emissions-month-1-1}

\subsubsection{EMEP-EU temporal schema:
annual}\label{emep-eu-temporal-schema-annual}

Source: EMEP v5.0 schema: data/temporal/EMEP4UKv5.0/

\begin{figure}[h]

{\centering \includegraphics[width=0.6\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/EU/annual/TPannual_allISO/plots/e2023/sox_EU_2023emis_2023map_2025inv_11_EUMONTOTLINE} 

}

\caption{Emissions of sox month-1}\label{fig:fig-montotEU}
\end{figure}

Total monthly emissions of sox in EU and ISOs nearest to UK/Eire. As
annual emissions input into NetCDF, using model profiles.

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0396}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0792}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0792}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0792}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0693}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0693}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0693}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0693}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0693}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0693}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0693}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0693}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0792}}
  >{\centering\arraybackslash}p{(\linewidth - 26\tabcolsep) * \real{0.0891}}@{}}
\caption{Total monthly sox emissions (kt)}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
ISO
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
ISO
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
EU & 1058.4 & 1056.7 & 1004.4 & 930.2 & 839.1 & 791.9 & 759.5 & 740.7 &
775.0 & 862.1 & 932.9 & 1008.9 & 10759.8 \\
FR & 8.2 & 8.6 & 7.5 & 7.3 & 6.3 & 5.6 & 5.3 & 4.8 & 5.0 & 6.0 & 6.6 &
7.2 & 78.4 \\
NL & 1.6 & 1.6 & 1.6 & 1.5 & 1.4 & 1.4 & 1.3 & 1.2 & 1.3 & 1.5 & 1.5 &
1.6 & 17.5 \\
BE & 2.0 & 2.1 & 2.1 & 2.0 & 1.8 & 1.8 & 1.5 & 1.4 & 1.6 & 1.8 & 1.9 &
1.9 & 21.9 \\
DE & 22.1 & 22.4 & 21.2 & 19.2 & 16.7 & 15.5 & 14.2 & 13.2 & 14.6 & 17.4
& 19.3 & 21.1 & 216.9 \\
ES & 9.9 & 10.3 & 8.7 & 7.9 & 7.6 & 7.1 & 6.9 & 6.0 & 6.1 & 7.1 & 7.7 &
8.5 & 93.8 \\
NOS & 2.0 & 2.0 & 2.0 & 2.0 & 2.0 & 2.0 & 2.0 & 2.0 & 2.0 & 2.0 & 2.0 &
2.0 & 24.0 \\
ATL & 9.2 & 9.2 & 9.2 & 9.2 & 9.2 & 9.2 & 9.2 & 9.2 & 9.2 & 9.2 & 9.2 &
9.2 & 110.4 \\
\end{longtable}

\newpage

\subsection{\texorpdfstring{SECTORAL EMISSIONS
MONTH\textsuperscript{-1}}{SECTORAL EMISSIONS MONTH-1}}\label{sectoral-emissions-month-1-1}

\subsubsection{EMEP-EU temporal schema:
annual}\label{emep-eu-temporal-schema-annual-1}

Source: EMEP v5.0 schema: data/temporal/EMEP4UKv5.0/

\begin{figure}[h]

{\centering \includegraphics[width=0.7\linewidth]{../outputs/NFC/BASE/EMEP4UKv5.0/inv2025/EU/annual/TPannual_allISO/plots/e2023/sox_EU_2023emis_2023map_2025inv_12_EUMONSECLINE} 

}

\caption{Emissions (kt) of sox month-1 sector-1}\label{fig:unnamed-chunk-17}
\end{figure}

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.1774}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0403}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0645}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0645}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0645}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0565}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0565}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0565}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0565}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0565}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0565}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0565}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0565}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0645}}
  >{\centering\arraybackslash}p{(\linewidth - 28\tabcolsep) * \real{0.0726}}@{}}
\caption{Monthly sox emissions (kt) per sector per ISO}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ISO
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
Sector
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ISO
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M3
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M4
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M5
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M6
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M7
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M8
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M9
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M10
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M11
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
M12
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Total
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
A\_PublicPower & EU & 510.7 & 485.1 & 457.1 & 447.6 & 412.9 & 386.2 &
378.6 & 375.3 & 393.4 & 436.1 & 466.6 & 493.3 & 5242.9 \\
B\_Industry & EU & 226.6 & 233.7 & 233.7 & 219.3 & 207.6 & 202.2 & 188.8
& 175.5 & 187.6 & 208.6 & 218.4 & 224.7 & 2526.7 \\
C\_OtherStationaryComb & EU & 250.7 & 266.8 & 241.3 & 190.3 & 145.7 &
130.3 & 119.5 & 118.2 & 121.7 & 144.1 & 175.5 & 219.7 & 2123.8 \\
D\_Fugitive & EU & 18.8 & 18.9 & 18.9 & 18.9 & 18.9 & 18.9 & 18.9 & 18.9
& 18.9 & 18.9 & 18.9 & 18.9 & 226.7 \\
E\_Solvents & EU & 2.6 & 2.7 & 2.7 & 2.8 & 2.8 & 2.9 & 2.9 & 2.9 & 2.9 &
2.9 & 2.7 & 2.7 & 33.5 \\
F\_RoadTransport & EU & 7.6 & 7.8 & 8.0 & 8.2 & 8.4 & 8.4 & 8.4 & 8.4 &
8.4 & 8.6 & 8.4 & 7.9 & 98.5 \\
G\_Shipping & EU & 33.3 & 33.5 & 33.8 & 33.9 & 33.9 & 34.0 & 33.9 & 33.3
& 33.5 & 33.9 & 33.8 & 33.5 & 404.3 \\
H\_Aviation & EU & 0.5 & 0.5 & 0.6 & 0.6 & 0.6 & 0.6 & 0.6 & 0.5 & 0.5 &
0.6 & 0.6 & 0.5 & 6.7 \\
I\_Offroad & EU & 2.8 & 3.0 & 3.1 & 3.2 & 3.2 & 3.3 & 3.2 & 3.0 & 3.1 &
3.2 & 3.1 & 2.9 & 37.1 \\
J\_Waste & EU & 0.6 & 0.6 & 0.6 & 0.6 & 0.6 & 0.6 & 0.6 & 0.6 & 0.6 &
0.6 & 0.6 & 0.6 & 7.2 \\
K\_AgriLivestock & EU & 0.0 & 0.0 & 0.0 & 0.0 & 0.0 & 0.0 & 0.0 & 0.0 &
0.0 & 0.0 & 0.0 & 0.0 & 0.0 \\
L\_AgriOther & EU & 1.4 & 1.4 & 2.0 & 2.2 & 1.8 & 1.7 & 1.5 & 1.5 & 1.6
& 1.8 & 1.7 & 1.5 & 20.1 \\
M\_Other & EU & 2.6 & 2.6 & 2.6 & 2.6 & 2.6 & 2.6 & 2.6 & 2.6 & 2.6 &
2.6 & 2.6 & 2.6 & 31.2 \\
Total & - & 1058.2 & 1056.6 & 1004.4 & 930.2 & 839.0 & 791.7 & 759.5 &
740.7 & 774.8 & 861.9 & 932.9 & 1008.8 & 10758.7 \\
\end{longtable}

\newpage

\section{TIME SERIES}\label{time-series}

\newpage

\subsection{EMISSIONS SECTORAL
CLASSIFICATIONS}\label{emissions-sectoral-classifications}

\subsubsection{UK data starts in SNAP sectors, Eire data in GNFR
sectors.}\label{uk-data-starts-in-snap-sectors-eire-data-in-gnfr-sectors.}

\begin{itemize}
\item
  All UK SNAP03 \& SNAP04 goes to B\_Industry.
\item
  All UK SNAP08 goes to I\_Offroad.
\item
  All UK SNAP10 goes to K\_AgriLivestock.
\end{itemize}

\begin{longtable}[]{@{}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.2683}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0732}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0854}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0488}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.0488}}
  >{\centering\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1220}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.3537}}@{}}
\caption{Sectoral lookup table, SNAP \textless--\textgreater{}
GNFR}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
GNFRlong
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SNAP
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
sec
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
s1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
s2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
EMEP\_sec
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
name
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedleft
GNFRlong
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
SNAP
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
sec
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
s1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
s2
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
EMEP\_sec
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
name
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
A\_PublicPower & 1 & sec01 & 1 & 1 & 1 & PublicPower \\
B\_Industry & 3 & sec02 & 3 & 3 & 2 & Industry \\
C\_OtherStationaryComb & 2 & sec03 & 2 & 2 & 3 & OtherStationaryComb \\
D\_Fugitive & 5 & sec04 & 5 & 5 & 4 & Fugitive \\
E\_Solvents & 6 & sec05 & 6 & 2 & 5 & Solvents \\
F\_RoadTransport & 7 & sec06 & 7 & 2 & 6 & RoadTransport \\
G\_Shipping & 8 & sec07 & 8 & 8 & 7 & Shipping \\
H\_Aviation & 8 & sec08 & 8 & 7 & 8 & Aviation \\
I\_Offroad & 8 & sec09 & 8 & 2 & 9 & Offroad \\
J\_Waste & 9 & sec10 & 9 & 6 & 10 & Waste \\
K\_AgriLivestock & 10 & sec11 & 10 & 2 & 11 & AgriLivestock \\
L\_AgriOther & 10 & sec12 & 10 & 2 & 12 & AgriOther \\
M\_Other & 11 & sec13 & 5 & 5 & 13 & Other \\
O\_AviCruise & NA & & NA & NA & NA & AviationCruise \\
P\_IntShipping & 8 & & NA & NA & NA & InternationalShipping \\
Q\_LULUCF & NA & & NA & NA & NA & LULUCF \\
& 1 & sec14 & 1 & 1 & 1 & PublicPower\_Point \\
& 1 & sec15 & 1 & 3 & 1 & PublicPower\_Area \\
& 7 & sec16 & 7 & 2 & 16 & RoadTransportExhaustGasoline \\
& 7 & sec17 & 7 & 2 & 17 & RoadTransportExhaustDiesel \\
& 7 & sec18 & 7 & 2 & 18 & RoadTransportExhaustLPGgas \\
& 7 & sec19 & 7 & 2 & 19 & RoadTransportNonExhaustOther \\
\end{longtable}

\end{document}
